apiVersion: apps/v1
kind: Deployment
metadata:
  name: heatlink-redis
  labels:
    app: heatlink-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heatlink-redis
  template:
    metadata:
      labels:
        app: heatlink-redis
    spec:
      containers:
        - name: heatlink-redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
