apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: vitoriatenorio/heatlink-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: heatlink-api-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: heatlink-api-configmap
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: heatlink-api-configmap
                  key: DB_NAME
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: heatlink-api-configmap
                  key: REDIS_HOST
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: heatlink-postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: heatlink-postgres-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
