apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: vitoriatenorio/heatlink-api:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "worker"
            - name: DB_HOST
              value: "heatlink-postgres"
            - name: DB_NAME
              value: "heatlink"
            - name: REDIS_HOST
              value: "heatlink-redis"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: heatlink-postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: heatlink-postgres-secret
                  key: POSTGRES_PASSWORD
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
