apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.redis.name }}
  labels:
    app: {{ .Values.global.redis.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.global.redis.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.redis.name }}
    spec:
      containers:
        - name: {{ .Values.global.redis.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
